package com.example.livelydarkness;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.app.PendingIntent;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;

import com.google.android.gms.location.FusedLocationProviderClient;
import com.google.android.gms.location.LocationRequest;
import com.google.android.gms.location.LocationServices;
import com.google.android.gms.tasks.OnFailureListener;
import com.google.android.gms.tasks.OnSuccessListener;

import java.io.File;
import java.io.FileReader;

public class MainActivity extends AppCompatActivity {
    private static final String TAG = "MainActivity";
    private static final long LOCATION_UPDATE_INTERVAL = 1000; // Interval in ms between location updates.
    private static final int LOCATION_PENDING_INTENT_RC = 234;

    private FusedLocationProviderClient fusedLocationProviderClient;
    private PendingIntent locationPendingIntent;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

    }

    /**
     * Function of reading the given file.
     * @return String that is "ENTER \d*...EXIT \d*..."
     */
    private String fileToStr() {

        // creating empty fodder file
        // need to replace with the file generated by geofence
        File dir = this.getFilesDir();
        File file = new File(dir, "fodder");

        StringBuilder builder = new StringBuilder();

        try {
            FileReader fr = new FileReader(file);

            for (int c = fr.read() ; c != -1 ; c = fr.read()) {
                builder.append((char) c);
            }
            fr.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return builder.toString();
    }

    private void startListeningToLocationUpdates() {
        fusedLocationProviderClient = LocationServices.getFusedLocationProviderClient(this);
        fusedLocationProviderClient.requestLocationUpdates(getLocationRequest(), getLocationPendingIntent())
                .addOnSuccessListener(this, new OnSuccessListener<Void>() {
                    @Override
                    public void onSuccess(Void aVoid) {
                        Log.i(TAG, "Location update enabled.");
                    }
                })
                .addOnFailureListener(this, new OnFailureListener() {
                    @Override
                    public void onFailure(@NonNull Exception e) {
                        Log.i(TAG, "Failed to enable location update.");
                    }
                });
    }

    private void stopListeningToLocationUpdates() {
        fusedLocationProviderClient.removeLocationUpdates(locationPendingIntent);
    }

    private LocationRequest getLocationRequest() {
        LocationRequest locationRequest =LocationRequest.create();
        locationRequest.setInterval(LOCATION_UPDATE_INTERVAL);
        locationRequest.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);
        return locationRequest;
    }

    private PendingIntent getLocationPendingIntent() {
        if (locationPendingIntent != null) {
            return locationPendingIntent;
        }
        Intent intent = new Intent(this, LocationBroadcastReceiver.class);
        locationPendingIntent = PendingIntent.getBroadcast(
                this,
                LOCATION_PENDING_INTENT_RC,
                intent,
                PendingIntent.FLAG_UPDATE_CURRENT
        );
        return locationPendingIntent;
    }
}
