package com.example.livelydarkness;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

import com.google.android.gms.location.LocationRequest;

import java.io.File;
import java.io.FileReader;

public class MainActivity extends AppCompatActivity {
    private static final long LOCATION_UPDATE_INTERVAL = 1000; // Interval in ms between location updates.

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

    }

    /**
     * Function of reading the given file.
     * @return String that is "ENTER \d*...EXIT \d*..."
     */
    private String fileToStr() {

        // creating empty fodder file
        // need to replace with the file generated by geofence
        File dir = this.getFilesDir();
        File file = new File(dir, "fodder");

        StringBuilder builder = new StringBuilder();

        try {
            FileReader fr = new FileReader(file);

            for (int c = fr.read() ; c != -1 ; c = fr.read()) {
                builder.append((char) c);
            }
            fr.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return builder.toString();
    }

    private LocationRequest getLocationRequest() {
        LocationRequest locationRequest =LocationRequest.create();
        locationRequest.setInterval(LOCATION_UPDATE_INTERVAL);
        locationRequest.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);
        return locationRequest;
    }
}
